language: python
python:
  - 2.7
install:
  - pip install -r requirements-dev.txt
  - pip install python-coveralls
  - pip install pytest-cov
  - python setup.py install
script:
  - paver test_all
  - paver coverage
after_success:
  - coveralls
